-- Domínio de commerce. Valores monetários em centavos (inteiros) para evitar erro de ponto flutuante.

CREATE TABLE customers (
  id                     serial PRIMARY KEY,
  name                   text        NOT NULL,
  email                  text        NOT NULL UNIQUE,
  city                   text        NOT NULL,
  notifications_opt_out  boolean     NOT NULL DEFAULT false,
  created_at             timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE products (
  id           serial PRIMARY KEY,
  sku          text    NOT NULL UNIQUE,
  name         text    NOT NULL,
  category     text    NOT NULL,
  price_cents  integer NOT NULL CHECK (price_cents > 0),
  active       boolean NOT NULL DEFAULT true
);

CREATE TABLE orders (
  id                   integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1001) PRIMARY KEY,
  customer_id          integer     NOT NULL REFERENCES customers(id),
  status               text        NOT NULL CHECK (status IN
                         ('pending_payment','paid','shipped','delivered','cancelled','refunded')),
  total_cents          integer     NOT NULL CHECK (total_cents >= 0),
  placed_at            timestamptz NOT NULL DEFAULT now(),
  expected_ship_by     timestamptz NOT NULL,
  shipped_at           timestamptz,
  delivered_at         timestamptz,
  cancelled_at         timestamptz,
  cancellation_reason  text
);
CREATE INDEX orders_customer_idx ON orders(customer_id);
CREATE INDEX orders_status_idx ON orders(status);
CREATE INDEX orders_placed_at_idx ON orders(placed_at);

CREATE TABLE order_items (
  id                serial  PRIMARY KEY,
  order_id          integer NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  product_id        integer NOT NULL REFERENCES products(id),
  quantity          integer NOT NULL CHECK (quantity > 0),
  unit_price_cents  integer NOT NULL CHECK (unit_price_cents > 0)
);
CREATE INDEX order_items_order_idx ON order_items(order_id);

CREATE TABLE payments (
  id             serial      PRIMARY KEY,
  order_id       integer     NOT NULL UNIQUE REFERENCES orders(id),
  method         text        NOT NULL CHECK (method IN ('pix','credit_card','boleto')),
  status         text        NOT NULL CHECK (status IN ('pending','captured','failed','voided','refunded')),
  amount_cents   integer     NOT NULL CHECK (amount_cents >= 0),
  created_at     timestamptz NOT NULL DEFAULT now(),
  captured_at    timestamptz,
  refunded_at    timestamptz,
  refund_reason  text
);

-- Conhecimento de schema vive no banco: inspectSchema lê estes comentários.
COMMENT ON TABLE customers IS 'Clientes da loja.';
COMMENT ON COLUMN customers.notifications_opt_out IS 'Cliente pediu para não receber notificações.';
COMMENT ON TABLE products IS 'Catálogo de produtos. price_cents = preço atual em centavos de BRL.';
COMMENT ON TABLE orders IS 'Pedidos. id é o número exibido ao usuário (#1001...).';
COMMENT ON COLUMN orders.status IS 'pending_payment | paid | shipped | delivered | cancelled | refunded';
COMMENT ON COLUMN orders.total_cents IS 'Total do pedido em centavos de BRL.';
COMMENT ON COLUMN orders.expected_ship_by IS 'Prazo prometido de envio. Pedido pago e não enviado após este prazo está atrasado.';
COMMENT ON TABLE order_items IS 'Itens de um pedido; unit_price_cents é o preço no momento da compra.';
COMMENT ON TABLE payments IS 'Um pagamento por pedido.';
COMMENT ON COLUMN payments.status IS 'pending | captured | failed | voided | refunded. Receita = captured.';
